"""added user

Revision ID: 095798b8d00b
Revises: c7cc4b4a08d6
Create Date: 2023-12-28 11:34:50.149977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "095798b8d00b"
down_revision = "c7cc4b4a08d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    oauth_table = op.create_table(
        "oauth_service",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("registration_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["oauth_service.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_user_id"), "user", ["user_id"], unique=False)
    op.add_column(
        "article", sa.Column("publish_date", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column("article", sa.Column("has_moderation", sa.Boolean(), nullable=False))
    op.add_column("article", sa.Column("author_id", sa.Integer(), nullable=True))
    op.alter_column(
        "article",
        "title",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.String(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "article",
        "anons",
        existing_type=sa.VARCHAR(length=400),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.create_foreign_key(
        None,
        "article",
        "user",
        ["author_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.drop_column("article", "update_date")
    # ### end Alembic commands ###
    op.bulk_insert(
        oauth_table,
        [
            {"id": 1, "service_name": "yandex"},
            {"id": 2, "service_name": "github"},
            {"id": 3, "service_name": "google"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "article",
        sa.Column(
            "update_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "article", type_="foreignkey")
    op.alter_column(
        "article",
        "anons",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=400),
        existing_nullable=False,
    )
    op.alter_column(
        "article",
        "title",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=120),
        existing_nullable=False,
    )
    op.drop_column("article", "author_id")
    op.drop_column("article", "has_moderation")
    op.drop_column("article", "publish_date")
    op.drop_index(op.f("ix_user_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_table("oauth_service")
    # ### end Alembic commands ###
