"""nullable topic quiz

Revision ID: 0fda9fbd8dd1
Revises: 34521abe89a2
Create Date: 2023-08-23 09:58:31.257417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0fda9fbd8dd1"
down_revision = "34521abe89a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("quiz", "topic_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint("quiz_topic_id_fkey", "quiz", type_="foreignkey")
    op.create_foreign_key(
        "quiz_topic_id_fkey",
        "quiz",
        "quiz_topic",
        ["topic_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("quiz_topic_id_fkey", "quiz", type_="foreignkey")
    op.create_foreign_key(
        "quiz_topic_id_fkey",
        "quiz",
        "quiz_topic",
        ["topic_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column("quiz", "topic_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
