"""fixed nullable status tag

Revision ID: 1ea31af743ad
Revises: c3657b47dcc9
Create Date: 2023-09-02 11:12:04.520648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1ea31af743ad"
down_revision = "c3657b47dcc9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "handbook_page",
        "short_description",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.String(length=160),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_answer",
        "explanation",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "quiz_question",
        "hint",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    op.alter_column("tag", "status_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tag", "status_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "quiz_question",
        "hint",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "quiz_answer",
        "explanation",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "handbook_page",
        "short_description",
        existing_type=sa.String(length=160),
        type_=sa.VARCHAR(length=120),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
