"""added unique filed

Revision ID: 1f382bcdb3da
Revises: e38c474f9ac6
Create Date: 2023-08-21 16:48:29.843917

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "1f382bcdb3da"
down_revision = "e38c474f9ac6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "handbook", ["title"])
    op.create_unique_constraint(None, "quiz_topic", ["title"])
    op.create_unique_constraint(None, "status", ["title"])
    op.create_unique_constraint(None, "tag", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tag", type_="unique")
    op.drop_constraint(None, "status", type_="unique")
    op.drop_constraint(None, "quiz_topic", type_="unique")
    op.drop_constraint(None, "handbook", type_="unique")
    # ### end Alembic commands ###
