"""updated quiz fields

Revision ID: 27d58c38f635
Revises: 38564344c4c0
Create Date: 2023-10-29 09:28:34.586041

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27d58c38f635"
down_revision = "38564344c4c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quiz",
        "description",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_question",
        "text",
        existing_type=sa.VARCHAR(length=400),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_answer",
        "text",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_answer",
        "explanation",
        existing_type=sa.VARCHAR(length=300),
        type_=sa.String(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quiz",
        "description",
        existing_type=sa.String(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_question",
        "text",
        existing_type=sa.String(),
        type_=sa.VARCHAR(length=400),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_answer",
        "explanation",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=300),
        existing_nullable=True,
    )
    op.alter_column(
        "quiz_answer",
        "text",
        existing_type=sa.String(length=500),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
