"""rename field meta

Revision ID: 3517acf5c25c
Revises: d1e219e855ec
Create Date: 2023-08-30 14:06:15.794142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3517acf5c25c"
down_revision = "d1e219e855ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handbook_page",
        sa.Column(
            "short_description",
            sa.String(length=160),
            nullable=False,
            server_default="",
        ),
    )
    op.drop_column("handbook_page", "meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handbook_page",
        sa.Column(
            "meta",
            sa.VARCHAR(length=120),
            autoincrement=False,
            nullable=False,
            server_default="",
        ),
    )
    op.drop_column("handbook_page", "short_description")
    # ### end Alembic commands ###
