"""add book table

Revision ID: 38564344c4c0
Revises: bfe3cc721fde
Create Date: 2023-10-21 18:29:20.257418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "38564344c4c0"
down_revision = "bfe3cc721fde"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("handbook_id", sa.Integer(), nullable=True),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=False),
        sa.Column("is_display", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["handbook_id"], ["handbook.id"], onupdate="SET NULL", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_book_id"), "book", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_id"), table_name="book")
    op.drop_table("book")
    # ### end Alembic commands ###
