"""update field for meta

Revision ID: 3f31e3ab6513
Revises: 0fda9fbd8dd1
Create Date: 2023-08-25 09:35:57.096650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f31e3ab6513"
down_revision = "0fda9fbd8dd1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz",
        sa.Column(
            "short_description",
            sa.String(length=160),
            nullable=False,
            server_default="",
        ),
    )
    op.drop_column("quiz", "meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz",
        sa.Column("meta", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    )
    op.drop_column("quiz", "short_description")
    # ### end Alembic commands ###
