"""added categories for handbook

Revision ID: 43ec38fcae2f
Revises: ddc773c65c62
Create Date: 2023-09-23 12:13:08.529763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "43ec38fcae2f"
down_revision = "ddc773c65c62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "handbook_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.add_column(
        "handbook",
        sa.Column("category_id", sa.Integer(), nullable=True, server_default=None),
    )
    op.create_foreign_key(
        None,
        "handbook",
        "handbook_category",
        ["category_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "handbook", type_="foreignkey")
    op.drop_column("handbook", "category_id")
    op.drop_table("handbook_category")
    # ### end Alembic commands ###
