"""rename table

Revision ID: 470d9cbf9f21
Revises: 1f382bcdb3da
Create Date: 2023-08-22 13:16:55.799243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "470d9cbf9f21"
down_revision = "1f382bcdb3da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("anons", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("reading_time", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_article_id"), "article", ["id"], unique=False)
    op.drop_index("ix_post_id", table_name="post")
    op.drop_table("post")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=80), autoincrement=False, nullable=False),
        sa.Column("anons", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "update_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "create_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("reading_time", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="post_pkey"),
    )
    op.create_index("ix_post_id", "post", ["id"], unique=False)
    op.drop_index(op.f("ix_article_id"), table_name="article")
    op.drop_table("article")
    # ### end Alembic commands ###
