"""initial

Revision ID: 50d5f4d79c82
Revises:
Create Date: 2023-08-13 11:20:11.442032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50d5f4d79c82"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("anons", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("reading_time", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_post_id"), "post", ["id"], unique=False)
    op.create_table(
        "quiz",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_id"), "quiz", ["id"], unique=False)
    op.create_table(
        "status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=25), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "handbook",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["status_id"], ["status.id"], onupdate="CASCADE", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quiz_question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quiz_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("hint", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["quiz.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_question_id"), "quiz_question", ["id"], unique=False)
    op.create_table(
        "handbook_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("handbook_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["handbook_id"],
            ["handbook.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_handbook_content_id"), "handbook_content", ["id"], unique=False
    )
    op.create_table(
        "quiz_answer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("explanation", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["quiz_question.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quiz_answer_id"), "quiz_answer", ["id"], unique=False)
    op.create_table(
        "handbook_page",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("meta", sa.String(length=120), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("reading_time", sa.Integer(), nullable=False),
        sa.Column("update_date", sa.DateTime(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["handbook_content.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_handbook_page_id"), "handbook_page", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_handbook_page_id"), table_name="handbook_page")
    op.drop_table("handbook_page")
    op.drop_index(op.f("ix_quiz_answer_id"), table_name="quiz_answer")
    op.drop_table("quiz_answer")
    op.drop_index(op.f("ix_handbook_content_id"), table_name="handbook_content")
    op.drop_table("handbook_content")
    op.drop_index(op.f("ix_quiz_question_id"), table_name="quiz_question")
    op.drop_table("quiz_question")
    op.drop_table("handbook")
    op.drop_table("status")
    op.drop_index(op.f("ix_quiz_id"), table_name="quiz")
    op.drop_table("quiz")
    op.drop_index(op.f("ix_post_id"), table_name="post")
    op.drop_table("post")
    # ### end Alembic commands ###
