"""added part for handbook

Revision ID: 5c60f6523458
Revises: 43ec38fcae2f
Create Date: 2023-09-28 14:34:08.850464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c60f6523458"
down_revision = "43ec38fcae2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handbook_content",
        sa.Column("part", sa.SmallInteger(), nullable=False, server_default="1"),
    )
    op.add_column(
        "handbook_page",
        sa.Column("subpart", sa.SmallInteger(), nullable=False, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("handbook_page", "subpart")
    op.drop_column("handbook_content", "part")
    # ### end Alembic commands ###
