"""added visible field  handbook

Revision ID: 5da49a5a4477
Revises: f83c9ab15fa2
Create Date: 2023-09-17 08:03:53.323553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5da49a5a4477"
down_revision = "f83c9ab15fa2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handbook",
        sa.Column("is_visible", sa.Boolean(), nullable=False, server_default="False"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("handbook", "is_visible")
    # ### end Alembic commands ###
