"""rename handbook status table

Revision ID: 6ac63be55613
Revises: c0ba7dfa9f7e
Create Date: 2023-09-02 17:34:21.581643

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "6ac63be55613"
down_revision = "c0ba7dfa9f7e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("status", "handbook_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("handbook_status", "status")
    # ### end Alembic commands ###
