"""udpated field for handbook

Revision ID: 8493e1bd9d81
Revises: d3dd02287441
Create Date: 2023-08-13 07:07:11.658430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8493e1bd9d81"
down_revision = "d3dd02287441"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handbook_content",
        sa.Column(
            "description", sa.String(length=255), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "handbook_page",
        sa.Column(
            "short_description",
            sa.String(length=120),
            nullable=False,
            server_default="",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("handbook_page", "short_description")
    op.drop_column("handbook_content", "description")
    # ### end Alembic commands ###
