"""minor fixed and added quiz topic

Revision ID: 8b09b812dca3
Revises: 50d5f4d79c82
Create Date: 2023-08-13 16:21:03.039385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b09b812dca3"
down_revision = "50d5f4d79c82"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_topic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(
        "handbook_content_handbook_id_fkey", "handbook_content", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "handbook_content",
        "handbook",
        ["handbook_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "handbook_page_content_id_fkey", "handbook_page", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "handbook_page",
        "handbook_content",
        ["content_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.add_column("quiz", sa.Column("topic_id", sa.Integer(), nullable=False))
    op.add_column("quiz", sa.Column("logo_url", sa.String(), nullable=True))
    op.add_column("quiz", sa.Column("meta", sa.String(length=80), nullable=False))
    op.alter_column("quiz", "description", existing_type=sa.VARCHAR(), nullable=False)
    op.create_foreign_key(
        None,
        "quiz",
        "quiz_topic",
        ["topic_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "quiz", type_="foreignkey")
    op.alter_column("quiz", "description", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("quiz", "meta")
    op.drop_column("quiz", "logo_url")
    op.drop_column("quiz", "topic_id")
    op.drop_constraint(None, "handbook_page", type_="foreignkey")
    op.create_foreign_key(
        "handbook_page_content_id_fkey",
        "handbook_page",
        "handbook_content",
        ["content_id"],
        ["id"],
    )
    op.drop_constraint(None, "handbook_content", type_="foreignkey")
    op.create_foreign_key(
        "handbook_content_handbook_id_fkey",
        "handbook_content",
        "handbook",
        ["handbook_id"],
        ["id"],
    )
    op.drop_table("quiz_topic")
    # ### end Alembic commands ###
