"""udpated field name

Revision ID: 9a6f75674746
Revises: 8493e1bd9d81
Create Date: 2023-08-13 07:17:59.592275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a6f75674746"
down_revision = "8493e1bd9d81"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handbook_page",
        sa.Column("meta", sa.String(length=120), nullable=False, server_default=""),
    )
    op.drop_column("handbook_page", "short_description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handbook_page",
        sa.Column(
            "short_description",
            sa.VARCHAR(length=120),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("handbook_page", "meta")
    # ### end Alembic commands ###
