"""added status tag

Revision ID: c3657b47dcc9
Revises: 3517acf5c25c
Create Date: 2023-08-31 13:43:21.459120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3657b47dcc9"
down_revision = "3517acf5c25c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.add_column("tag", sa.Column("status_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None,
        "tag",
        "tag_status",
        ["status_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tag", type_="foreignkey")
    op.drop_column("tag", "status_id")
    op.drop_table("tag_status")
    # ### end Alembic commands ###
