"""added user

Revision ID: d1a881b5c528
Revises: c7cc4b4a08d6
Create Date: 2023-12-24 13:57:42.857962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1a881b5c528"
down_revision = "c7cc4b4a08d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    oauth_table = op.create_table(
        "oauth_service",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("registration_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["oauth_service.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_user_id"), "user", ["user_id"], unique=False)
    # ### end Alembic commands ###
    op.bulk_insert(
        oauth_table,
        [
            {"id": 1, "service_name": "yandex"},
            {"id": 2, "service_name": "github"},
            {"id": 3, "service_name": "google"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_table("oauth_service")
    # ### end Alembic commands ###
