"""rename field

Revision ID: d1e219e855ec
Revises: 3f31e3ab6513
Create Date: 2023-08-25 16:19:23.246120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1e219e855ec"
down_revision = "3f31e3ab6513"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz_answer",
        sa.Column("text", sa.String(length=255), nullable=False, server_default=""),
    )
    op.drop_column("quiz_answer", "title")
    op.add_column(
        "quiz_question",
        sa.Column("text", sa.String(length=255), nullable=False, server_default=""),
    )
    op.drop_column("quiz_question", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz_question",
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.drop_column("quiz_question", "text")
    op.add_column(
        "quiz_answer",
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.drop_column("quiz_answer", "text")
    # ### end Alembic commands ###
