"""deleted slug

Revision ID: d3dd02287441
Revises: eacc48c5eb2a
Create Date: 2023-08-11 11:29:41.226197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3dd02287441"
down_revision = "eacc48c5eb2a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("handbook_page_slug_key", "handbook_page", type_="unique")
    op.drop_column("handbook_page", "slug")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handbook_page",
        sa.Column("slug", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("handbook_page_slug_key", "handbook_page", ["slug"])
    # ### end Alembic commands ###
