"""added visible field for quiz

Revision ID: ddc773c65c62
Revises: 5da49a5a4477
Create Date: 2023-09-17 11:37:30.032183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddc773c65c62"
down_revision = "5da49a5a4477"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz",
        sa.Column("is_visible", sa.Boolean(), nullable=False, server_default="True"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quiz", "is_visible")
    # ### end Alembic commands ###
