"""delete visible field

Revision ID: e38c474f9ac6
Revises: a3df76d3e434
Create Date: 2023-08-15 20:09:53.185471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e38c474f9ac6"
down_revision = "a3df76d3e434"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("handbook", "is_visible")
    op.drop_column("handbook_content", "is_visible")
    op.drop_column("handbook_page", "is_visible")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handbook_page",
        sa.Column("is_visible", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "handbook_content",
        sa.Column("is_visible", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "handbook",
        sa.Column("is_visible", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
