"""initial

Revision ID: f2d9e36c059e
Revises:
Create Date: 2023-08-11 07:14:27.746332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2d9e36c059e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("handbook", sa.Column("logo_url", sa.String(), nullable=True))
    op.add_column(
        "handbook", sa.Column("is_complemented", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "handbook_page", sa.Column("content_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        "handbook_page_handbook_title_id_fkey", "handbook_page", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "handbook_page", "handbook_content", ["content_id"], ["id"]
    )
    op.drop_column("handbook_page", "handbook_title_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "handbook_page",
        sa.Column(
            "handbook_title_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "handbook_page", type_="foreignkey")
    op.create_foreign_key(
        "handbook_page_handbook_title_id_fkey",
        "handbook_page",
        "handbook_content",
        ["handbook_title_id"],
        ["id"],
    )
    op.drop_column("handbook_page", "content_id")
    op.drop_column("handbook", "is_complemented")
    op.drop_column("handbook", "logo_url")
    # ### end Alembic commands ###
