"""Initial2

Revision ID: f76c269aeea5
Revises: e3eabd64da97
Create Date: 2023-08-06 09:39:40.054708

"""


# revision identifiers, used by Alembic.
revision = "f76c269aeea5"
down_revision = "e3eabd64da97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
