"""added news project

Revision ID: f83c9ab15fa2
Revises: a25bfcc107a5
Create Date: 2023-09-12 15:10:40.212553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f83c9ab15fa2"
down_revision = "a25bfcc107a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("reading_time", sa.Integer(), nullable=False),
        sa.Column("create_date", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_news")
    # ### end Alembic commands ###
