version: "3.8"

services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    restart: unless-stopped
    ports:
      - "25:25"
      - "465:465"
      - "993:993"
    environment:
      - OVERRIDE_HOSTNAME=mail.dropmecode.ru
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mail.dropmecode.ru
      - ONE_DIR=1
      - ENABLE_AMAVIS=1
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_FAIL2BAN=1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dms/mail-data/:/var/mail/
      - ./dms/mail-state/:/var/mail-state/
      - ./dms/config:/tmp/docker-mailserver/
      - ../certificates/acme.json:/etc/letsencrypt/acme.json:ro
    cap_add:
      - NET_ADMIN

  whoami:
    container_name: whoami
    image: traefik/whoami:latest
    restart: unless-stopped
    command:
      - --port=8005
      - --name=iamfoo
    expose:
      - 8005
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`mail.dropmecode.ru`) && Path(`/health`)" # change
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
